version: '3.8'
services:
  ragai:
    build: ./app
    container_name: agent-fw
    ports:
      - 3000:8080
    volumes:
      - ./sqldb:/sqldb:rw
      - ./app/app/:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  web_app:
    build: ./web
    container_name: web_app
    ports:
      - 5555:5555
    depends_on:
      - ragai
