version: '3.8'
services:
  python_app:
    build: ./app
    container_name: python_app
    ports:
      - 8080:3000
    volumes:
      - ./sqldb:/sqldb
      - ./vdb:/vdb
  web_app:
    build: ./web
    container_name: web_app
    ports:
      - 5555:5555
    depends_on:
      - python_app
